apiVersion: v2

version: 0.1
deprecated: false

name: jarvice
appVersion: "3.0.1"
description: JARVICE cloud platform
home: http://www.nimbix.net/
maintainers:
    - name: Nimbix, Inc.
      email: support@nimbix.net
      url: http://www.nimbix.net/
keywords:
    - JARVICE
    - HPC
    - cloud
icon: https://github.com/nimbix/jarvice-helm/raw/master/skin-default/favicon.png
sources:
   - https://github.com/nimbix/jarvice-helm

engine: gotpl
kubeVersion: ">=1.14.0-0"
dependencies:
- name: keycloak
  repository: "https://codecentric.github.io/helm-charts/"
  version: "17.0.3"
  condition: keycloak.enabled