{{- if .Values.jarvice_pod_scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-pod-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-pod-scheduler
    deployment: jarvice-pod-scheduler
    jarvice-system: core
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: jarvice-pod-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-pod-scheduler
        deployment: jarvice-pod-scheduler
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_pod_scheduler.tolerations)) }}
      tolerations: {{ .Values.jarvice_pod_scheduler.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_pod_scheduler.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_pod_scheduler.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
{{- if (not (empty .Values.jarvice_pod_scheduler.nodeAffinity)) }}
      affinity:
        nodeAffinity: {{ .Values.jarvice_pod_scheduler.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
      affinity:
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      hostAliases:
      {{- include "jarvice.hostAliases" . | nindent 8 }}
      containers:
      - name: jarvice-pod-scheduler
{{- if .Values.jarvice.JARVICE_SYSTEM_OMIT_REPO_BASE }}
        image: {{ include "jarvice.registry" . }}/jarvice-pod-scheduler:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- else }}
        image: {{ include "jarvice.registry" . }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-pod-scheduler:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- end }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        readinessProbe:
          exec:
            command:
            - /bin/true
          initialDelaySeconds: {{ .Values.jarvice_pod_scheduler.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_pod_scheduler.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_pod_scheduler.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_pod_scheduler.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_pod_scheduler.readinessProbe.failureThreshold }}
        livenessProbe:
          exec:
            command:
            - /bin/true
          initialDelaySeconds: {{ .Values.jarvice_pod_scheduler.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_pod_scheduler.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_pod_scheduler.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_pod_scheduler.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_pod_scheduler.livenessProbe.failureThreshold }}
        env:
{{- if .Values.jarvice_bird.enabled }}
          - name: JARVICE_BIRD_API_URL
            value: "{{ .Values.jarvice_bird.ingressHost }}/portal"
{{- end }}
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_POD_SCHED_NAME
{{- if empty .Values.jarvice_pod_scheduler.JARVICE_POD_SCHED_NAME }}
            value: "{{ .Release.Namespace }}"
{{- else }}
            value: "{{ .Values.jarvice_pod_scheduler.env.JARVICE_POD_SCHED_NAME }}"
{{- end }}
          - name: JARVICE_POD_SCHED_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_POD_SCHED_LOGLEVEL }}"
          - name: JARVICE_POD_SCHED_LICENSE_PRE
{{- if (not (empty .Values.jarvice.JARVICE_POD_SCHED_LICENSE_PRE)) }}
            value: "{{ .Values.jarvice.JARVICE_POD_SCHED_LICENSE_PRE }}"
{{- else }}
            value: "false"
{{- end }}
          - name: JARVICE_POD_SCHED_MULTIPLIERS
            value: '{{ .Values.jarvice.JARVICE_POD_SCHED_MULTIPLIERS }}'
{{- if (not (empty .Values.jarvice.JARVICE_POD_SCHED_WORKERS)) }}
          - name: MAX_WORKER_THREADS
            value: "{{ .Values.jarvice.JARVICE_POD_SCHED_WORKERS }}"
{{- end }}
          - name: JARVICE_JOBS_MULTI_TENANT
            value: "{{ .Values.jarvice.JARVICE_JOBS_MULTI_TENANT }}"
{{- if and .Values.jarvice_license_manager.enabled (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_URL) }}
          - name: JARVICE_LICENSE_MANAGER_URL
            value: "http://jarvice-license-manager:8080"
{{- else if (not (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_URL)) }}
          - name: JARVICE_LICENSE_MANAGER_URL
            value: "{{ .Values.jarvice.JARVICE_LICENSE_MANAGER_URL }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_SSL_VERIFY)) }}
          - name: JARVICE_LICENSE_MANAGER_SSL_VERIFY
            value: "{{ .Values.jarvice.JARVICE_LICENSE_MANAGER_SSL_VERIFY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_KEY)) }}
          - name: JARVICE_LICENSE_MANAGER_KEY
            valueFrom:
              secretKeyRef:
                name: jarvice-license-manager
                key: JARVICE_LICENSE_MANAGER_KEY
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTP_PROXY)) }}
          - name: http_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTP_PROXY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTPS_PROXY)) }}
          - name: https_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTPS_PROXY }}"
{{- end }}
{{- if or .Values.jarvice.JARVICE_HTTPS_PROXY .Values.jarvice.JARVICE_HTTP_PROXY .Values.jarvice.JARVICE_NO_PROXY }}
{{- if (not (empty .Values.jarvice.JARVICE_NO_PROXY)) }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }},{{ .Values.jarvice.JARVICE_NO_PROXY }}'
{{- else }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }}'
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.jarvice_pod_scheduler.resources | indent 10 }}
{{- end }}
