{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_smtpd.enabled }}
{{- if gt (.Values.jarvice_smtpd.replicaCount | int) 1 }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-smtpd
spec:
  selector:
    matchLabels:
      deployment: jarvice-smtpd
  minAvailable: {{ .Values.jarvice_smtpd.pdb.minAvailable }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-smtpd
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-smtpd
    deployment: jarvice-smtpd
spec:
  replicas: {{ .Values.jarvice_smtpd.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-smtpd
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-smtpd
        deployment: jarvice-smtpd
    spec:
{{- if (not (empty .Values.jarvice_smtpd.tolerations)) }}
      tolerations: {{ .Values.jarvice_smtpd.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_smtpd.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_smtpd.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
{{- if (not (empty .Values.jarvice_smtpd.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice_smtpd.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
        podAntiAffinity:
        {{- if eq .Values.jarvice_smtpd.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-smtpd
        {{- else if eq .Values.jarvice_smtpd.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-smtpd
        {{- end }}
{{- if .Values.jarvice_registry_proxy.enabled }}
      imagePullSecrets:
      - name: jarvice-docker
{{- end }}
{{- if (not (empty .Values.jarvice.cacert.configMap)) }}
      volumes:
      - name: ca-jarvice-user
        configMap:
          name: {{ .Values.jarvice.cacert.configMap }}
          optional: true
          defaultMode: 444
{{- end }}
      containers:
      - name: jarvice-smtpd
        image: {{ template "jarvice.registrysub" merge (dict "image" .Values.jarvice_smtpd.image) . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.jarvice_smtpd.imagePullPolicy }}
        ports:
          - name: "smtp"
            containerPort: 25
        readinessProbe:
          tcpSocket:
            port: smtp
          initialDelaySeconds: {{ .Values.jarvice_smtpd.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.jarvice_smtpd.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: smtp
          initialDelaySeconds: {{ .Values.jarvice_smtpd.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.jarvice_smtpd.livenessProbe.timeoutSeconds }}
{{- if (not (empty .Values.jarvice.cacert.configMap)) }}
        volumeMounts:
        - name: ca-jarvice-user
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
          readOnly: true
{{- end }}
        resources:
{{ toYaml .Values.jarvice_smtpd.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-smtpd
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-smtpd
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 25
    targetPort: 25
    name: smtp
  selector:
    deployment: jarvice-smtpd
---
{{- if or .Values.jarvice_smtpd.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_smtpd.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-smtpd
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-smtpd
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 25
  - from:
    - namespaceSelector:
        matchLabels:
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
          name: {{ .Release.Namespace }}-builds
{{- else }}
          name: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 25
  - from:
    - namespaceSelector:
        matchLabels:
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
          name: {{ .Release.Namespace }}-pulls
{{- else }}
          name: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 25
---
{{- end }}
{{- end }}
{{- end }}
