{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_api.enabled }}
{{- if gt (.Values.jarvice_api.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-api
spec:
  selector:
    matchLabels:
      deployment: jarvice-api
  minAvailable: {{ .Values.jarvice_api.pdb.minAvailable }}
---
{{- end }}
{{- if gt (.Values.jarvice_api.replicaCountMax | int) (.Values.jarvice_api.replicaCount | int) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jarvice-api
  minReplicas: {{ .Values.jarvice_api.replicaCount }}
  maxReplicas: {{ .Values.jarvice_api.replicaCountMax }}
  metrics:
    {{- toYaml .Values.jarvice_api.autoscaling.metrics | nindent 4 }}
---
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
    deployment: jarvice-api
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_api.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-api
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-api
        deployment: jarvice-api
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_api.tolerations)) }}
      tolerations: {{ .Values.jarvice_api.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_api.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_api.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
{{- if (not (empty .Values.jarvice_api.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice_api.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
        podAntiAffinity:
        {{- if eq .Values.jarvice_api.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-api
        {{- else if eq .Values.jarvice_api.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-api
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      containers:
      - name: jarvice-api
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-api:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /jarvice/ready
          initialDelaySeconds: {{ .Values.jarvice_api.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_api.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_api.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_api.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_api.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /jarvice/live
          initialDelaySeconds: {{ .Values.jarvice_api.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_api.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_api.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_api.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_api.livenessProbe.failureThreshold }}
        env:
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_DAL_URL
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: "http://jarvice-dal.{{ .Release.Namespace }}:8080"
{{- else }}
            value: "http://jarvice-dal.{{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}:8080"
{{- end }}
          - name: JARVICE_API_URL
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: "http://jarvice-api.{{ .Release.Namespace }}:8080"
{{- else }}
            value: "http://jarvice-api.{{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}:8080"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_API_PUBLIC_URL)) }}
          - name: JARVICE_API_PUBLIC_URL
            value: "{{ .Values.jarvice.JARVICE_API_PUBLIC_URL }}"
{{- else if (not (empty .Values.jarvice_api.ingressHost)) }}
          - name: JARVICE_API_PUBLIC_URL
{{- if or (eq "lookupip" .Values.jarvice_api.ingressHost) (eq "-" .Values.jarvice_api.ingressHost) }}
            value: 'https://{{- (first (lookup "v1" "Service" .Values.jarvice_api.ingressServiceNamespace .Values.jarvice_api.ingressService).status.loadBalancer.ingress).ip }}{{ .Values.jarvice_api.ingressPath }}'
{{- else if eq "lookup" .Values.jarvice_api.ingressHost }}
            value: 'https://{{- (first (lookup "v1" "Service" .Values.jarvice_api.ingressServiceNamespace .Values.jarvice_api.ingressService).status.loadBalancer.ingress).hostname }}{{ .Values.jarvice_api.ingressPath }}'
{{- else }}
            value: "https://{{ .Values.jarvice_api.ingressHost }}{{ .Values.jarvice_api.ingressPath }}"
{{- end }}
{{- end }}
          - name: JARVICE_SCHED_URL
            value: "https://jarvice-scheduler:9443"
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_BUILDS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
            value: {{ .Release.Namespace }}-builds
{{- else }}
            value: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
          - name: JARVICE_PULLS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
            value: {{ .Release.Namespace }}-pulls
{{- else }}
            value: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
{{- if .Values.jarvice_api.env }}
{{- if empty .Values.jarvice_api.env.JARVICE_IMAGES_TAG }}
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- else }}
            value: {{ .Values.jarvice_api.env.JARVICE_IMAGES_TAG }}
{{- end }}
{{- else }}
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- end }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
{{- if (not (empty .Values.jarvice_dockerbuild.tolerations)) }}
          - name: JARVICE_BUILD_NODE_TOLERATIONS
            value: '{{ .Values.jarvice_dockerbuild.tolerations }}'
{{- else if (not (empty .Values.jarvice.tolerations)) }}
          - name: JARVICE_BUILD_NODE_TOLERATIONS
            value: '{{ .Values.jarvice.tolerations }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.tolerations)) }}
          - name: JARVICE_PULL_NODE_TOLERATIONS
            value: '{{ .Values.jarvice_dockerpull.tolerations }}'
{{- else if (not (empty .Values.jarvice.tolerations)) }}
          - name: JARVICE_PULL_NODE_TOLERATIONS
            value: '{{ .Values.jarvice.tolerations }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerbuild.nodeSelector)) }}
          - name: JARVICE_BUILD_NODE_SELECTOR
            value: '{{ .Values.jarvice_dockerbuild.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_BUILD_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.nodeSelector)) }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: '{{ .Values.jarvice_dockerpull.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- $smtpd := printf "jarvice-smtpd.%s:25" .Release.Namespace -}}
{{- if (not (empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE)) }}
{{- $smtpd = printf "jarvice-smtpd.%s:25" .Values.jarvice.JARVICE_SYSTEM_NAMESPACE -}}
{{- end }}
          - name: JARVICE_MAIL_FROM
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_FROM | indent 12 }}
          - name: JARVICE_MAIL_ADMINS
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_ADMINS | indent 12 }}
          - name: JARVICE_MAIL_SERVER
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_SERVER | replace "jarvice-smtpd:25" $smtpd | indent 12 }}
          - name: JARVICE_MAIL_USERNAME
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_USERNAME | indent 12 }}
{{- if (not (empty .Values.JARVICE_MAIL_PASSWORD)) }}
          - name: JARVICE_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-mail
                key: JARVICE_MAIL_PASSWORD
{{- end }}
          - name: JARVICE_API_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_API_LOGLEVEL }}"
        resources:
{{ toYaml .Values.jarvice_api.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-api
---
{{- if or .Values.jarvice_api.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_api.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-api
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-api
  policyTypes:
  - Ingress
  ingress:
{{- if (empty .Values.jarvice_api.ingressHost) }}
  - {}
{{- else }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
---
{{- end }}
{{- if (empty .Values.jarvice_api.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_api.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-api
---
{{- else }}
apiVersion: {{ template "apiVersion.ingress" . }}
kind: Ingress
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  rules:
  - http:
      paths:
{{- if (eq "/api" .Values.jarvice_api.ingressPath) }}
      - backend:
          serviceName: jarvice-api
          servicePort: http
        path: /api
{{- else }}
      - backend:
          serviceName: jarvice-api
          servicePort: http
        path: /
{{- end }}
{{- if ne "-" .Values.jarvice_api.ingressHost }}
{{- if eq "lookup" .Values.jarvice_api.ingressHost }}
    host: '{{- (first (lookup "v1" "Service" .Values.jarvice_api.ingressServiceNamespace .Values.jarvice_api.ingressService).status.loadBalancer.ingress).hostname }}'
{{- else }}
    host: {{ .Values.jarvice_api.ingressHost }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
