{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_appsync.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-appsync
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-appsync
    deployment: jarvice-appsync
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_appsync.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-appsync
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-appsync
        deployment: jarvice-appsync
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_appsync.tolerations)) }}
      tolerations: {{ .Values.jarvice_appsync.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_appsync.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_appsync.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
{{- if (not (empty .Values.jarvice_appsync.nodeAffinity)) }}
      affinity:
        nodeAffinity: {{ .Values.jarvice_appsync.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
      affinity:
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
      imagePullSecrets:
      - name: jarvice-docker
{{- if (not (empty .Values.jarvice.cacert.user.configMap)) }}
      volumes:
      - name: ca-jarvice-user
        configMap:
          name: {{ .Values.jarvice.cacert.user.configMap }}
          optional: false
          defaultMode: 444
{{- end }}
      hostAliases:
      {{- include "jarvice.hostAliases" . | nindent 8 }}
      containers:
      - name: jarvice-appsync
        image: {{ include "jarvice.registry" . }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-appsync:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /usr/bin/curl -s -k  http://jarvice-dal:8080/ready | grep -q OK
          initialDelaySeconds: {{ .Values.jarvice_appsync.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_appsync.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_appsync.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_appsync.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_appsync.readinessProbe.failureThreshold }}
        livenessProbe:
          exec:
            command:
            - /bin/true
          initialDelaySeconds: {{ .Values.jarvice_appsync.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_appsync.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_appsync.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_appsync.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_appsync.livenessProbe.failureThreshold }}
        env:
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_DAL_URL
            value: "http://jarvice-dal:8080"
          - name: JARVICE_LOCAL_API_URL
            value: "http://jarvice-api:8080"
          - name: JARVICE_APP_USER
            value: "jarvice"
          - name: JARVICE_REMOTE_API_URL
            value: "{{ .Values.jarvice.JARVICE_REMOTE_API_URL }}"
          - name: JARVICE_REMOTE_USER
            valueFrom:
              secretKeyRef:
                name: jarvice-appsync
                key: JARVICE_REMOTE_USER
          - name: JARVICE_REMOTE_APIKEY
            valueFrom:
              secretKeyRef:
                name: jarvice-appsync
                key: JARVICE_REMOTE_APIKEY
          - name: JARVICE_APPSYNC_USERONLY
            value: "{{ .Values.jarvice.JARVICE_APPSYNC_USERONLY }}"
{{- if (not (empty .Values.jarvice.JARVICE_HTTP_PROXY)) }}
          - name: http_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTP_PROXY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTPS_PROXY)) }}
          - name: https_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTPS_PROXY }}"
{{- end }}
{{- if or .Values.jarvice.JARVICE_HTTPS_PROXY .Values.jarvice.JARVICE_HTTP_PROXY .Values.jarvice.JARVICE_NO_PROXY }}
{{- if (not (empty .Values.jarvice.JARVICE_NO_PROXY)) }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }},{{ .Values.jarvice.JARVICE_NO_PROXY }}'
{{- else }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }}'
{{- end }}
{{- end }}
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
{{- if (not (empty .Values.jarvice_appsync.env.JARVICE_SYSTEM_REGISTRY)) }}
            value: "{{ .Values.jarvice_appsync.env.JARVICE_SYSTEM_REGISTRY }}"
{{- else }}
            value: "{{ include "jarvice.registry" . }}"
{{- end }}
          - name: JARVICE_SYSTEM_REPO_BASE
{{- if (not (empty .Values.jarvice_appsync.env.JARVICE_SYSTEM_REPO_BASE)) }}
            value: "{{ .Values.jarvice_appsync.env.JARVICE_SYSTEM_REPO_BASE }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}"
{{- end }}
          - name: JARVICE_APPSYNC_INTERVAL
            value: "{{ .Values.jarvice_appsync.env.JARVICE_APPSYNC_INTERVAL }}"
{{- if (not (empty .Values.jarvice.cacert.user.configMap)) }}
        volumeMounts:
        - name: ca-jarvice-user
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
          readOnly: true
{{- end }}
        resources:
{{ toYaml .Values.jarvice_appsync.resources | indent 10 }}
{{- end }}
{{- end }}
