{{- if .Values.jarvice.trust_manager.enabled }}
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: jarvice-root-cert
spec:
  sources:
  - useDefaultCAs: true
  - inLine: |
{{- if (eq "letsencrypt-staging" .Values.jarvice.ingress.tls.issuer.name) }}
{{- $files := .Files }}
{{ $files.Get "files/lets-encrypt-staging.pem" | indent 6 }}
{{- end }}
{{- if (not (empty .Values.jarvice.trust_manager.inLine)) }}
{{ .Values.jarvice.trust_manager.inLine | indent 6 }}
{{- end }}
  target:
    configMap:
      key: "ca-certificates.crt"
    additionalFormats:
      jks:
        key: "cacerts"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
