{{- if .Values.jarvice_kns_scheduler.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kns-sa
  namespace: jarvice-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kns-crb
subjects:
- kind: ServiceAccount
  name: kns-sa
  namespace: jarvice-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
{{- if gt (.Values.jarvice_kns_scheduler.replicaCount | int) 1 }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-kns-scheduler
spec:
  selector:
    matchLabels:
      deployment: jarvice-kns-scheduler
  minAvailable: {{ .Values.jarvice_kns_scheduler.pdb.minAvailable }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-kns-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-kns-scheduler
    deployment: jarvice-kns-scheduler
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_kns_scheduler.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-kns-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-kns-scheduler
        deployment: jarvice-kns-scheduler
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccount: kns-sa
      serviceAccountName: kns-sa
{{- if (not (empty .Values.jarvice_kns_scheduler.tolerations)) }}
      tolerations: {{ .Values.jarvice_kns_scheduler.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_kns_scheduler.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
{{- if (not (empty .Values.jarvice_kns_scheduler.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice_kns_scheduler.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
        podAntiAffinity:
        {{- if eq .Values.jarvice_kns_scheduler.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-kns-scheduler
        {{- else if eq .Values.jarvice_kns_scheduler.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-kns-scheduler
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      volumes:
      {{- include "jarvice.rootCertVolume" . | indent 6 }}
      hostAliases:
      {{- include "jarvice.hostAliases" . | nindent 8 }}
      containers:
      - name: jarvice-kns-scheduler
        command: ["python3"]
        args: ["/main", "Nested"]
        image: {{ include "jarvice.registry" . }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-k8s-nested-scheduler:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /ready
          initialDelaySeconds: {{ .Values.jarvice_kns_scheduler.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_kns_scheduler.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_kns_scheduler.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_kns_scheduler.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_kns_scheduler.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /live
          initialDelaySeconds: {{ .Values.jarvice_kns_scheduler.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_kns_scheduler.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_kns_scheduler.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_kns_scheduler.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_kns_scheduler.livenessProbe.failureThreshold }}
        env:
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEEP_VCLUSTERS)) }}
          - name: JARVICE_KNS_KEEP_VCLUSTERS
            value: "{{ .Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEEP_VCLUSTERS }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_DEFAULT_LIMIT_RANGE)) }}
          - name: JARVICE_KNS_DEFAULT_LIMIT_RANGE
            value: "{{ .Values.jarvice_kns_scheduler.env.JARVICE_KNS_DEFAULT_LIMIT_RANGE }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_VCLUSTER_SPAWN_DELAY)) }}
          - name: JARVICE_KNS_VCLUSTER_SPAWN_DELAY
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_VCLUSTER_SPAWN_DELAY }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_INIT_IMAGE)) }}
          - name: JARVICE_KNS_INIT_IMAGE
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_INIT_IMAGE }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_ALLOW_GOTTY_SHELL)) }}
          - name: JARVICE_KNS_ALLOW_GOTTY_SHELL
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_ALLOW_GOTTY_SHELL }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_GOTTY_IMAGE)) }}
          - name: JARVICE_KNS_GOTTY_IMAGE
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_GOTTY_IMAGE }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_GOTTY_IMAGE_TAG)) }}
          - name: JARVICE_KNS_GOTTY_IMAGE_TAG
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_GOTTY_IMAGE_TAG }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_URL)) }}
          - name: JARVICE_KNS_KEYCLOAK_URL
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_URL }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_REALM)) }}
          - name: JARVICE_KNS_KEYCLOAK_REALM
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_REALM }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_CLIENT_ID)) }}
          - name: JARVICE_KNS_KEYCLOAK_CLIENT_ID
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_CLIENT_ID }}"
{{- end }}
{{- if (not (empty .Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_CLIENT_SECRET)) }}
          - name: JARVICE_KNS_KEYCLOAK_CLIENT_SECRET
            value: "{{ $.Values.jarvice_kns_scheduler.env.JARVICE_KNS_KEYCLOAK_CLIENT_SECRET }}"
{{- end }}
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_CLUSTER_TYPE
{{- if empty .Values.jarvice.JARVICE_CLUSTER_TYPE }}
            value: "downstream"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_CLUSTER_TYPE }}"
{{- end }}
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ include "jarvice.registry" . }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
          - name: JARVICE_K8S_ADMIN_CONF
            value: "{{ .Values.jarvice_kns_scheduler.env.JARVICE_K8S_ADMIN_CONF }}"
          - name: JARVICE_SCHED_PLUGIN_USE
            value: "true"
{{- if (not (empty .Values.jarvice.JARVICE_HTTP_PROXY)) }}
          - name: http_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTP_PROXY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTPS_PROXY)) }}
          - name: https_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTPS_PROXY }}"
{{- end }}
{{- if or .Values.jarvice.JARVICE_HTTPS_PROXY .Values.jarvice.JARVICE_HTTP_PROXY .Values.jarvice.JARVICE_NO_PROXY }}
{{- if (not (empty .Values.jarvice.JARVICE_NO_PROXY)) }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }},{{ .Values.jarvice.JARVICE_NO_PROXY }}'
{{- else }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }}'
{{- end }}
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_JOBS_DOMAIN)) }}
          - name: JARVICE_JOBS_DOMAIN
{{- if (hasPrefix "lookup" .Values.jarvice.JARVICE_JOBS_DOMAIN) }}
{{- if (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE) }}
            value: '{{- .Values.jarvice_kns_scheduler.ingressHost -}}{{- trimPrefix "lookup" .Values.jarvice.JARVICE_JOBS_DOMAIN -}}'
{{- else }}
            value: '{{- .Values.jarvice_mc_portal.ingressHost -}}{{- trimPrefix "lookup" .Values.jarvice.JARVICE_JOBS_DOMAIN -}}'
{{- end }}
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_JOBS_DOMAIN }}"
{{- end }}
{{- end }}
          - name: JARVICE_JOBS_INGRESS_CLASS
            value: "{{ .Values.jarvice.ingress.class }}"
          - name: JARVICE_JOBS_INGRESS_ANNOTATIONS
            value: '{{ .Values.jarvice.JARVICE_JOBS_INGRESS_ANNOTATIONS }}'
{{- if and (not (empty .Values.jarvice.ingress.tls.crt)) (not (empty .Values.jarvice.ingress.tls.key)) }}
          - name: JARVICE_JOBS_INGRESS_CERT_SECRET_NAME
            value: "tls-jarvice"
{{- else }}
{{- if (not (empty .Values.jarvice.ingress.tls.issuer.name)) }}
          - name: JARVICE_JOBS_INGRESS_CERT_ISSUER
            value: "{{ .Values.jarvice.ingress.tls.issuer.name }}"
{{- else if (not (empty .Values.jarvice.ingress.tls.cluster_issuer.name)) }}
          - name: JARVICE_JOBS_INGRESS_CERT_CLUSTER_ISSUER
            value: "{{ .Values.jarvice.ingress.tls.cluster_issuer.name }}"
{{- end }}
{{- end }}
          - name: JARVICE_K8S_SCHED_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_K8S_SCHED_LOGLEVEL }}"
        resources:
{{- if .Values.jarvice_kns_scheduler.resources }}
{{ toYaml .Values.jarvice_kns_scheduler.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-kns-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-kns-scheduler
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-kns-scheduler
---
{{- if or .Values.jarvice_kns_scheduler.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_kns_scheduler.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-kns-scheduler
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-kns-scheduler
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- if (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE) }}
{{- if (empty .Values.jarvice_kns_scheduler.ingressHost) }}
  - {}
{{- else }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
{{- end }}
---
{{- end }}
{{- if (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE) }}
{{- if (empty .Values.jarvice_kns_scheduler.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: jarvice-kns-scheduler-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-kns-scheduler
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_kns_scheduler.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-kns-scheduler
---
{{- else }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: jarvice-kns-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-kns-scheduler
  annotations:
{{- if (not (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion)) }}
{{- if (not (empty .Values.jarvice.ingress.class)) }}
    kubernetes.io/ingress.class: {{ .Values.jarvice.ingress.class }}
{{- end }}
{{- end }}
{{- if and (not (empty .Values.jarvice.ingress.tls.issuer.name)) (and (empty .Values.jarvice.ingress.tls.crt) (empty .Values.jarvice.ingress.tls.key)) }}
    cert-manager.io/issuer: {{ .Values.jarvice.ingress.tls.issuer.name }}
{{- else if and (not (empty .Values.jarvice.ingress.tls.cluster_issuer.name)) (and (empty .Values.jarvice.ingress.tls.crt) (empty .Values.jarvice.ingress.tls.key)) }}
    cert-manager.io/cluster-issuer: {{ .Values.jarvice.ingress.tls.cluster_issuer.name }}
{{- end }}
{{- if .Values.jarvice_kns_scheduler.ingressAnnotations }}
{{- if (kindIs "string" .Values.jarvice_kns_scheduler.ingressAnnotations) }}
{{ toYaml (fromJson .Values.jarvice_kns_scheduler.ingressAnnotations) | indent 4 }}
{{- else }}
{{ toYaml .Values.jarvice_kns_scheduler.ingressAnnotations | indent 4 }}
{{- end }}
{{- end }}
spec:
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if (not (empty .Values.jarvice.ingress.class)) }}
  ingressClassName: {{ .Values.jarvice.ingress.class }}
{{- end }}
{{- end }}
  rules:
  - http:
      paths:
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
      - backend:
          service:
            name: jarvice-kns-scheduler
            port:
              name: http
        pathType: Prefix
        path: /
{{- else }}
      - backend:
          serviceName: jarvice-kns-scheduler
          servicePort: http
{{- end }}
{{- if ne "-" .Values.jarvice_kns_scheduler.ingressHost }}
    host: '{{- .Values.jarvice_kns_scheduler.ingressHost -}}'
{{- if or (not (empty .Values.jarvice.ingress.tls.cluster_issuer.name)) (not (empty .Values.jarvice.ingress.tls.issuer.name)) (and (not (empty .Values.jarvice.ingress.tls.crt)) (not (empty .Values.jarvice.ingress.tls.key))) }}
  tls:
  - hosts:
    - '{{- .Values.jarvice_kns_scheduler.ingressHost -}}'
{{- if and (not (empty .Values.jarvice.ingress.tls.crt)) (not (empty .Values.jarvice.ingress.tls.key)) }}
    secretName: 'tls-jarvice'
{{- else }}
    secretName: 'tls-{{- .Values.jarvice_kns_scheduler.ingressHost -}}'
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
