{{- if .Values.jarvice_idmapper.enabled }}
{{- if gt (.Values.jarvice_idmapper.replicaCount | int) 1 }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-idmapper
spec:
  selector:
    matchLabels:
      deployment: jarvice-idmapper
  minAvailable: {{ .Values.jarvice_idmapper.pdb.minAvailable }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-idmapper
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-idmapper
    deployment: jarvice-idmapper
spec:
  replicas: {{ .Values.jarvice_idmapper.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-idmapper
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-idmapper
        deployment: jarvice-idmapper
    spec:
{{- if (not (empty .Values.jarvice_idmapper.tolerations)) }}
      tolerations: {{ .Values.jarvice_idmapper.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_idmapper.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_idmapper.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
{{- if (not (empty .Values.jarvice_idmapper.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice_idmapper.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
        podAntiAffinity:
        {{- if eq .Values.jarvice_idmapper.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-idmapper
        {{- else if eq .Values.jarvice_idmapper.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-idmapper
        {{- end }}
{{- if .Values.jarvice_registry_proxy.enabled }}
      imagePullSecrets:
      - name: jarvice-docker
{{- end }}
      containers:
      - name: jarvice-idmapper
        image: {{ template "jarvice.registrysub" merge (dict "image" .Values.jarvice_idmapper.image) . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.jarvice_idmapper.imagePullPolicy }}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            port: http
            path: /map/
          initialDelaySeconds: {{ .Values.jarvice_idmapper.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_idmapper.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_idmapper.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_idmapper.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_idmapper.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            port: http
            path: /map/
          initialDelaySeconds: {{ .Values.jarvice_idmapper.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_idmapper.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_idmapper.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_idmapper.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_idmapper.livenessProbe.failureThreshold }}
        env:
{{- if .Values.jarvice_bird.enabled }}
          - name: JARVICE_BIRD_API_URL
            value: "{{ .Values.jarvice_bird.ingressHost }}/portal"
{{- end }}
          - name: HOMEPATH
            value: "{{ .Values.jarvice_idmapper.env.HOMEPATH }}"
          - name: UPNPATH
            value: "{{ .Values.jarvice_idmapper.env.UPNPATH }}"
{{- if (not (empty .Values.jarvice.JARVICE_HTTP_PROXY)) }}
          - name: http_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTP_PROXY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTPS_PROXY)) }}
          - name: https_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTPS_PROXY }}"
{{- end }}
{{- if or .Values.jarvice.JARVICE_HTTPS_PROXY .Values.jarvice.JARVICE_HTTP_PROXY .Values.jarvice.JARVICE_NO_PROXY }}
{{- if (not (empty .Values.jarvice.JARVICE_NO_PROXY)) }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }},{{ .Values.jarvice.JARVICE_NO_PROXY }}'
{{- else }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }}'
{{- end }}
{{- end }}
        volumeMounts:
        - mountPath: /home
          name: homes
          readOnly: true
{{- if (not (empty .Values.jarvice.cacert.user.configMap)) }}
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
          readOnly: true
          name: ca-jarvice-user
{{- end }}
        resources:
{{ toYaml .Values.jarvice_idmapper.resources | indent 10 }}
      volumes:
{{- if (not (empty .Values.jarvice.cacert.user.configMap)) }}
        - name: ca-jarvice-user
          configMap:
            name: {{ .Values.jarvice.cacert.user.configMap }}
            optional: true
            defaultMode: 444
{{- end }}
        - name: homes
{{- if (not (empty .Values.jarvice_idmapper.filesystem.server)) }}
          nfs:
            path:  {{ .Values.jarvice_idmapper.filesystem.path }}
            server: {{ .Values.jarvice_idmapper.filesystem.server }}
{{- else }}
          hostPath:
            path:  {{ .Values.jarvice_idmapper.filesystem.path }}
            type: Directory
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-idmapper
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-idmapper
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-idmapper
---
{{- if or .Values.jarvice_idmapper.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_idmapper.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-idmapper
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-idmapper
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
---
{{- end }}
{{- end }}
