{{- if and .Values.jarvice_db.enabled .Values.jarvice_db.persistence.enabled (not (empty .Values.jarvice_db.persistence.storageClass)) (not (empty .Values.jarvice_db.persistence.storageClassProvisioner)) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.jarvice_db.persistence.storageClass }}
reclaimPolicy: Delete
provisioner: {{ .Values.jarvice_db.persistence.storageClassProvisioner }}
{{- if (eq "kubernetes.io/aws-ebs" .Values.jarvice_db.persistence.storageClassProvisioner) }}
parameters:
  type: gp2
mountOptions:
  - debug
{{- end }}
{{- if (eq "kubernetes.io/gce-pd" .Values.jarvice_db.persistence.storageClassProvisioner) }}
parameters:
  type: pd-standard
  replication-type: none
mountOptions:
  - debug
{{- end }}
{{- if (eq "kubernetes.io/azure-disk" .Values.jarvice_db.persistence.storageClassProvisioner) }}
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
volumeBindingMode: Immediate
{{- end }}
---
{{- end }}
{{- if and (not (empty .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS)) (not (empty .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS_PROVISIONER)) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS }}
reclaimPolicy: Delete
provisioner: {{ .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS_PROVISIONER }}
{{- if (eq "kubernetes.io/aws-ebs" .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS_PROVISIONER) }}
parameters:
  type: gp2
mountOptions:
  - debug
{{- end }}
{{- if (eq "kubernetes.io/gce-pd" .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS_PROVISIONER) }}
parameters:
  type: pd-standard
  replication-type: none
mountOptions:
  - debug
{{- end }}
{{- if (eq "kubernetes.io/azure-disk" .Values.jarvice.JARVICE_PVC_VAULT_STORAGECLASS_PROVISIONER) }}
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
volumeBindingMode: Immediate
{{- end }}
---
{{- end }}
{{- if and .Values.jarvice_dockerbuild.persistence.enabled (not (empty .Values.jarvice_dockerbuild.persistence.storageClass)) (not (empty .Values.jarvice_dockerbuild.persistence.storageClassProvisioner)) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.jarvice_dockerbuild.persistence.storageClass }}
reclaimPolicy: Delete
provisioner: {{ .Values.jarvice_dockerbuild.persistence.storageClassProvisioner }}
{{- if (eq "kubernetes.io/aws-ebs" .Values.jarvice_dockerbuild.persistence.storageClassProvisioner) }}
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - debug
{{- end }}
{{- if (eq "kubernetes.io/gce-pd" .Values.jarvice_dockerbuild.persistence.storageClassProvisioner) }}
parameters:
  type: pd-standard
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - debug
{{- end }}
{{- if (eq "pd.csi.storage.gke.io" .Values.jarvice_dockerbuild.persistence.storageClassProvisioner) }}
parameters:
  type: pd-ssd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
{{- if (eq "kubernetes.io/azure-disk" .Values.jarvice_dockerbuild.persistence.storageClassProvisioner) }}
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
---
{{- end }}
{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if and .Values.jarvice_bird_server.persistence.enabled (not (empty .Values.jarvice_bird_server.persistence.storageClass)) (not (empty .Values.jarvice_bird_server.persistence.storageClassProvisioner)) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.jarvice_bird_server.persistence.storageClass }}
reclaimPolicy: Delete
provisioner: {{ .Values.jarvice_bird_server.persistence.storageClassProvisioner }}
{{- if (eq "kubernetes.io/aws-ebs" .Values.jarvice_bird_server.persistence.storageClassProvisioner) }}
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - debug
{{- end }}
{{- if (eq "kubernetes.io/gce-pd" .Values.jarvice_bird_server.persistence.storageClassProvisioner) }}
parameters:
  type: pd-standard
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - debug
{{- end }}
{{- if (eq "pd.csi.storage.gke.io" .Values.jarvice_bird_server.persistence.storageClassProvisioner) }}
parameters:
  type: pd-standard
  type: pd-ssd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
{{- if (eq "kubernetes.io/azure-disk" .Values.jarvice_bird_server.persistence.storageClassProvisioner) }}
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
volumeBindingMode: Immediate
  storageaccounttype: Premium_LRS
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
---
{{- end }}
{{- end }}