{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_db.enabled }}
{{- if and .Values.jarvice_db.persistence.enabled (empty .Values.jarvice_db.persistence.existingClaimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvice-db-pvc
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-db
{{- if eq .Values.jarvice_db.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
spec:
  accessModes:
    - {{ .Values.jarvice_db.persistence.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.jarvice_db.persistence.size }}
{{- if .Values.jarvice_db.persistence.storageClass }}
{{- if (eq "-" .Values.jarvice_db.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.jarvice_db.persistence.storageClass }}"
{{- end }}
{{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-db
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-db
    deployment: jarvice-db
spec:
  replicas: {{ .Values.jarvice_db.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deployment: jarvice-db
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-db
        deployment: jarvice-db
    spec:
{{- if (not (empty .Values.jarvice_db.tolerations)) }}
      tolerations: {{ .Values.jarvice_db.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_db.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_db.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
{{- if (not (empty .Values.jarvice_db.nodeAffinity)) }}
      affinity:
        nodeAffinity: {{ .Values.jarvice_db.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
      affinity:
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
{{- if .Values.jarvice_registry_proxy.enabled }}
      imagePullSecrets:
      - name: jarvice-docker
{{- end }}
      hostAliases:
      {{- include "jarvice.hostAliases" . | nindent 8 }}
      containers:
      - name: jarvice-db
        image: {{ template "jarvice.registrysub" merge (dict "image" .Values.jarvice_db.image) . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.jarvice_db.imagePullPolicy }}
        #command:
        #  - docker-entrypoint.sh
        #  - --ignore-db-dir=lost+found
        ports:
          - name: "jarvice-db"
            containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: jarvice-db
          initialDelaySeconds: {{ .Values.jarvice_db.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.jarvice_db.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: jarvice-db
          initialDelaySeconds: {{ .Values.jarvice_db.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.jarvice_db.livenessProbe.timeoutSeconds }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-db
{{- if (not (empty .Values.jarvice_db.env.MYSQL_ROOT_PASSWORD)) }}
                key: MYSQL_ROOT_PASSWORD
{{- else }}
                key: JARVICE_DBPASSWD
{{- end }}
{{- if or (not (empty .Values.jarvice_db.env.MYSQL_USER)) (ne "root" .Values.jarvice.JARVICE_DBUSER) }}
          - name: MYSQL_USER
{{- if (not (empty .Values.jarvice_db.env.MYSQL_USER)) }}
            value: "{{ .Values.jarvice_db.env.MYSQL_USER }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_DBUSER }}"
{{- end }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
{{- if (not (empty .Values.jarvice_db.env.MYSQL_PASSWORD)) }}
                key: MYSQL_PASSWORD
{{- else }}
                key: JARVICE_DBPASSWD
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.jarvice_db.resources | indent 10 }}
{{- if .Values.jarvice_db.persistence.enabled }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data-vol
      volumes:
        - name: db-data-vol
          persistentVolumeClaim:
{{- if (empty .Values.jarvice_db.persistence.existingClaimName) }}
            claimName: jarvice-db-pvc
{{- else }}
            claimName: {{ .Values.jarvice_db.persistence.existingClaimName }}
{{- end }}
{{- end }}
{{- if .Values.jarvice_db.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.jarvice_db.securityContext.fsGroup }}
        runAsUser: {{ .Values.jarvice_db.securityContext.runAsUser }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-db
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-db
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: jarvice-db
  selector:
    deployment: jarvice-db
---
{{- if or .Values.jarvice_db.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_db.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-db
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 3306
---
{{- end }}
{{- end }}
{{- end }}
