{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_mc_portal.enabled }}
{{- if gt (.Values.jarvice_mc_portal.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-mc-portal
spec:
  selector:
    matchLabels:
      deployment: jarvice-mc-portal
  minAvailable: {{ .Values.jarvice_mc_portal.pdb.minAvailable }}
---
{{- end }}
{{- if gt (.Values.jarvice_mc_portal.replicaCountMax | int) (.Values.jarvice_mc_portal.replicaCount | int) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jarvice-mc-portal
  minReplicas: {{ .Values.jarvice_mc_portal.replicaCount }}
  maxReplicas: {{ .Values.jarvice_mc_portal.replicaCountMax }}
  metrics:
    {{- toYaml .Values.jarvice_mc_portal.autoscaling.metrics | nindent 4 }}
---
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
    deployment: jarvice-mc-portal
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_mc_portal.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-mc-portal
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-mc-portal
        deployment: jarvice-mc-portal
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
{{- if (not (empty .Values.jarvice_mc_portal.tolerations)) }}
      tolerations: {{ .Values.jarvice_mc_portal.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_mc_portal.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.jarvice_mc_portal.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-mc-portal
        {{- else if eq .Values.jarvice_mc_portal.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-mc-portal
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      volumes:
        - name: jarvice-settings
          configMap:
            name: {{ .Values.jarvice.settings.configMap }}
            optional: true
        - name: jarvice-secrets
          secret:
            secretName: jarvice-secrets
            optional: true
        - name: krb5-keytab
          secret:
            secretName: krb5.keytab
            defaultMode: 0644
            items:
            - key: krb5.keytab
              mode: 0644
              path: krb5.keytab
      containers:
      - name: jarvice-mc-portal
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-mc-portal:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /ready
          initialDelaySeconds: {{ .Values.jarvice_mc_portal.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_mc_portal.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_mc_portal.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_mc_portal.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_mc_portal.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /live
          initialDelaySeconds: {{ .Values.jarvice_mc_portal.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_mc_portal.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_mc_portal.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_mc_portal.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_mc_portal.livenessProbe.failureThreshold }}
        env:
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_DAL_URL
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_DAL_URL)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_DAL_URL }}"
{{- else }}
            value: "http://jarvice-dal:8080"
{{- end }}
          - name: JARVICE_API_URL
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_API_URL)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_API_URL }}"
{{- else }}
            value: "http://jarvice-api:8080"
{{- end }}
          - name: JARVICE_USER_DEFAULT_ENABLED
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_USER_DEFAULT_ENABLED }}"
          - name: JARVICE_USER_DEFAULT_DEVELOPER
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_USER_DEFAULT_DEVELOPER }}"
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_GSS_REALM)) }}
          - name: JARVICE_PORTAL_GSS_REALM
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_GSS_REALM }}"
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_GSS_DOMAIN)) }}
          - name: JARVICE_PORTAL_GSS_DOMAIN
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_GSS_DOMAIN }}"
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_GSS_LOG)) }}
          - name: JARVICE_PORTAL_GSS_LOG
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_GSS_LOG }}"
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_DISABLE_API_SUBST_WARNING)) }}
          - name: JARVICE_DISABLE_API_SUBST_WARNING
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_DISABLE_API_SUBST_WARNING }}"
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_WEB_HOST)) }}
          - name: JARVICE_PORTAL_WEB_HOST
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_WEB_HOST }}"
{{- else if (not (empty .Values.jarvice_mc_portal.ingressHost)) }}
          - name: JARVICE_PORTAL_WEB_HOST
            value: "https://{{ .Values.jarvice_mc_portal.ingressHost }}{{ .Values.jarvice_mc_portal.ingressPath }}"
{{- end }}
          - name: JARVICE_PORTAL_MEMCACHED_LOCATIONS
{{- if and .Values.jarvice_memcached.enabled (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MEMCACHED_LOCATIONS) }}
            {{- $memcachedCount := .Values.jarvice_memcached.replicaCount }}
            value: "
              {{- range $i, $none := until (int $memcachedCount) }}
                {{- if gt $i 0}},{{- end }}jarvice-memcached-{{ $i }}.jarvice-memcached:11211
              {{- end }}"
{{- else }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MEMCACHED_LOCATIONS }}"
{{- end }}
          - name: JARVICE_PORTAL_APP_OWNERS
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_APP_OWNERS }}"
          - name: JARVICE_PORTAL_MAIL_FROM
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_FROM)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_FROM }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_PORTAL_MAIL_FROM }}"
{{- end }}
          - name: JARVICE_PORTAL_MAIL_SUBJECT
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_SUBJECT)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_SUBJECT }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_PORTAL_MAIL_SUBJECT }}"
{{- end }}
          - name: JARVICE_PORTAL_MAIL_SERVER
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_SERVER)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_SERVER }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_MAIL_SERVER }}"
{{- end }}
          - name: JARVICE_PORTAL_MAIL_USERNAME
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_USERNAME)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_USERNAME }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_MAIL_USERNAME }}"
{{- end }}
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_PASSWORD)) }}
          - name: JARVICE_PORTAL_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-mc-portal
                key: JARVICE_PORTAL_MAIL_PASSWORD
{{- else if (not (empty .Values.jarvice.JARVICE_MAIL_PASSWORD)) }}
          - name: JARVICE_PORTAL_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-mail
                key: JARVICE_MAIL_PASSWORD
{{- end }}
          - name: JARVICE_PORTAL_MAIL_ADMINS
{{- if (not (empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_ADMINS)) }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_MAIL_ADMINS }}"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_MAIL_ADMINS }}"
{{- end }}
          - name: JARVICE_PORTAL_DB
{{- if empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DB }}
            value: "nimbix_portal_ng"
{{- else }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DB }}"
{{- end }}
          - name: JARVICE_PORTAL_DBHOST
{{- if empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBHOST }}
            value: "{{ .Values.jarvice.JARVICE_DBHOST }}"
{{- else }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBHOST }}"
{{- end }}
          - name: JARVICE_PORTAL_DBUSER
{{- if empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBUSER }}
            value: "{{ .Values.jarvice.JARVICE_DBUSER }}"
{{- else }}
            value: "{{ .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBUSER }}"
{{- end }}
          - name: JARVICE_PORTAL_DBPASSWD
            valueFrom:
              secretKeyRef:
                name: jarvice-db
{{- if empty .Values.jarvice_mc_portal.env.JARVICE_PORTAL_DBPASSWD }}
                key: JARVICE_DBPASSWD
{{- else }}
                key: JARVICE_PORTAL_DBPASSWD
{{- end }}
        volumeMounts:
        - name: jarvice-settings
          mountPath: /etc/jarvice/settings/jarvice-mc-portal
          readOnly: true
        - name: jarvice-secrets
          mountPath: /etc/jarvice/secrets/jarvice-mc-portal
          readOnly: true
        - name: krb5-keytab
          mountPath: /etc/krb5.keytab
          subPath: krb5.keytab
          readOnly: true
        resources:
{{- if .Values.jarvice_mc_portal.resources }}
{{ toYaml .Values.jarvice_mc_portal.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-mc-portal
---
{{- if or .Values.jarvice_mc_portal.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_mc_portal.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-mc-portal
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-mc-portal
  policyTypes:
  - Ingress
  ingress:
{{- if (empty .Values.jarvice_mc_portal.ingressHost) }}
  - {}
{{- else }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
---
{{- end }}
{{- if (empty .Values.jarvice_mc_portal.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: jarvice-mc-portal-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_mc_portal.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-mc-portal
---
{{- else }}
apiVersion: {{ template "apiVersion.ingress" . }}
kind: Ingress
metadata:
  name: jarvice-mc-portal
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-mc-portal
spec:
  rules:
  - http:
      paths:
{{- if (eq "/portal" .Values.jarvice_mc_portal.ingressPath) }}
      - backend:
          serviceName: jarvice-mc-portal
          servicePort: http
        path: /portal
      - backend:
          serviceName: jarvice-mc-portal
          servicePort: http
        path: /static
      - backend:
          serviceName: jarvice-mc-portal
          servicePort: http
        path: /index.html
{{- else }}
      - backend:
          serviceName: jarvice-mc-portal
          servicePort: http
        path: /
{{- end }}
{{- if ne "-" .Values.jarvice_mc_portal.ingressHost }}
{{- if eq "lookup" .Values.jarvice_mc_portal.ingressHost }}
    host: '{{- (first (lookup "v1" "Service" .Values.jarvice_mc_portal.ingressServiceNamespace .Values.jarvice_mc_portal.ingressService).status.loadBalancer.ingress).hostname }}'
{{- else }}
    host: {{ .Values.jarvice_mc_portal.ingressHost }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
