{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_scheduler.enabled }}
{{- if gt (.Values.jarvice_scheduler.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jarvice-scheduler
spec:
  selector:
    matchLabels:
      deployment: jarvice-scheduler
  minAvailable: {{ .Values.jarvice_scheduler.pdb.minAvailable }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
    deployment: jarvice-scheduler
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_scheduler.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-scheduler
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-scheduler
        deployment: jarvice-scheduler
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
      securityContext:
        runAsUser: 0
{{- if (not (empty .Values.jarvice_scheduler.tolerations)) }}
      tolerations: {{ .Values.jarvice_scheduler.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_scheduler.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_scheduler.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
{{- if (not (empty .Values.jarvice_scheduler.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice_scheduler.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
        podAntiAffinity:
        {{- if eq .Values.jarvice_scheduler.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-scheduler
        {{- else if eq .Values.jarvice_scheduler.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-scheduler
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      volumes:
        - name: jarvice-settings
          configMap:
            name: {{ .Values.jarvice.settings.configMap }}
            optional: true
            defaultMode: 0555
      containers:
      - name: jarvice-scheduler
        image: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-scheduler:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        ports:
          - name: https
            containerPort: 9443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /ready
          initialDelaySeconds: {{ .Values.jarvice_scheduler.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_scheduler.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_scheduler.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_scheduler.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_scheduler.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: https
            path: /live
          initialDelaySeconds: {{ .Values.jarvice_scheduler.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_scheduler.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_scheduler.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_scheduler.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_scheduler.livenessProbe.failureThreshold }}
        env:
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_DAL_URL
{{- if (not (empty .Values.jarvice_scheduler.env.JARVICE_DAL_URL)) }}
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_DAL_URL }}"
{{- else }}
            value: "http://jarvice-dal:8080"
{{- end }}
          - name: JARVICE_SCHED_URL
{{- if (not (empty .Values.jarvice_scheduler.env.JARVICE_SCHED_URL)) }}
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_SCHED_URL }}"
{{- else }}
            value: "https://jarvice-scheduler:9443"
{{- end }}
          - name: JARVICE_LICENSE_LIC
            valueFrom:
              secretKeyRef:
                name: jarvice-license
                key: JARVICE_LICENSE_LIC
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REGISTRY }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
          - name: JARVICE_K8S_ADMIN_CONF
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_K8S_ADMIN_CONF }}"
          - name: JARVICE_SCHED_PLUGIN_USE
{{- if or (not (empty .Values.jarvice.JARVICE_DEFAULT_CLUSTER_URL)) .Values.jarvice_k8s_scheduler.enabled }}
            value: "false"
{{- else }}
            value: "true"
{{- end }}
          - name: JARVICE_SCHED_PASS_INTERVAL
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_SCHED_PASS_INTERVAL }}"
          - name: JARVICE_SCHED_CLUSTERS_TIMEOUT
            value: "{{ .Values.jarvice_scheduler.env.JARVICE_SCHED_CLUSTERS_TIMEOUT }}"
{{- if .Values.jarvice_idmapper.enabled }}
          - name: JARVICE_IDMAPPER_URL
            value: "http://jarvice-idmapper:8080"
{{- end }}
          - name: JARVICE_SCHED_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_SCHED_LOGLEVEL }}"
          - name: JARVICE_SCHED_PASS_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_SCHED_PASS_LOGLEVEL }}"
          - name: JARVICE_MAIL_FROM
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_FROM | indent 12 }}
          - name: JARVICE_MAIL_ADMINS
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_ADMINS | indent 12 }}
          - name: JARVICE_MAIL_SERVER
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_SERVER | indent 12 }}
          - name: JARVICE_MAIL_USERNAME
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_USERNAME | indent 12 }}
{{- if (not (empty .Values.JARVICE_MAIL_PASSWORD)) }}
          - name: JARVICE_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-mail
                key: JARVICE_MAIL_PASSWORD
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_MAIL_CONF)) }}
          - name: JARVICE_MAIL_CONF
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_CONF | indent 12 }}
{{- end }}
{{- if and .Values.jarvice_license_manager.enabled (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_URL) }}
          - name: JARVICE_LICENSE_MANAGER_URL
            value: "http://jarvice-license-manager:8080"
{{- else if (not (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_URL)) }}
          - name: JARVICE_LICENSE_MANAGER_URL
            value: "{{ .Values.jarvice.JARVICE_LICENSE_MANAGER_URL }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_SSL_VERIFY)) }}
          - name: JARVICE_LICENSE_MANAGER_SSL_VERIFY
            value: "{{ .Values.jarvice.JARVICE_LICENSE_MANAGER_SSL_VERIFY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_LICENSE_MANAGER_KEY)) }}
          - name: JARVICE_LICENSE_MANAGER_KEY
            valueFrom:
              secretKeyRef:
                name: jarvice-license-manager
                key: JARVICE_LICENSE_MANAGER_KEY
{{- end }}
        volumeMounts:
        - name: jarvice-settings
          mountPath: /etc/jarvice/settings
          readOnly: true
        resources:
{{- if .Values.jarvice_scheduler.resources }}
{{ toYaml .Values.jarvice_scheduler.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
    name: https
  selector:
    deployment: jarvice-scheduler
---
{{- if or .Values.jarvice_scheduler.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_scheduler.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-scheduler
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-scheduler
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 9443
{{/*
WARNING: Enabling ingressHost for this service is dangerous.
DO NOT enable it here without understanding the security implications!
*/}}
{{- if (not (empty .Values.jarvice_scheduler.ingressHost)) }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 9443
{{- end }}
---
{{- end }}
{{/*
WARNING: Enabling ingressHost for this service is dangerous.
DO NOT enable it here without understanding the security implications!
*/}}
{{- if (not (empty .Values.jarvice_scheduler.ingressHost)) }}
apiVersion: {{ template "apiVersion.ingress" . }}
kind: Ingress
metadata:
  name: jarvice-scheduler
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-scheduler
spec:
  rules:
  - host: {{ .Values.jarvice_scheduler.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: jarvice-scheduler
          servicePort: https
---
{{- end }}
{{- end }}
{{- end }}
