{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_api.enabled }}
{{- if gt (.Values.jarvice_api.replicaCount | int) 1 }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-api
spec:
  selector:
    matchLabels:
      deployment: jarvice-api
  minAvailable: {{ .Values.jarvice_api.pdb.minAvailable }}
---
{{- end }}
{{- if gt (.Values.jarvice_api.replicaCountMax | int) (.Values.jarvice_api.replicaCount | int) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jarvice-api
  minReplicas: {{ .Values.jarvice_api.replicaCount }}
  maxReplicas: {{ .Values.jarvice_api.replicaCountMax }}
  metrics:
    {{- toYaml .Values.jarvice_api.autoscaling.metrics | nindent 4 }}
---
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
    deployment: jarvice-api
    jarvice-system: core
spec:
  replicas: {{ .Values.jarvice_api.replicaCount }}
  selector:
    matchLabels:
      deployment: jarvice-api
  template:
    metadata:
      labels:
        {{- include "jarvice.release_labels" . | indent 8 }}
        component: jarvice-api
        deployment: jarvice-api
        jarvice-system: core
      annotations:
        deployment-date: {{ now | quote }}
    spec:
      serviceAccountName: jarvice-system
{{- if (not (empty .Values.jarvice_api.tolerations)) }}
      tolerations: {{ .Values.jarvice_api.tolerations }}
{{- else if (not (empty .Values.jarvice.tolerations)) }}
      tolerations: {{ .Values.jarvice.tolerations }}
{{- end }}
{{- if (not (empty .Values.jarvice_api.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice_api.nodeSelector }}
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
      nodeSelector: {{ .Values.jarvice.nodeSelector }}
{{- end }}
      affinity:
{{- if (not (empty .Values.jarvice_api.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice_api.nodeAffinity }}
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
        nodeAffinity: {{ .Values.jarvice.nodeAffinity }}
{{- end }}
        podAntiAffinity:
        {{- if eq .Values.jarvice_api.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                deployment: jarvice-api
        {{- else if eq .Values.jarvice_api.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  deployment: jarvice-api
        {{- end }}
      imagePullSecrets:
      - name: jarvice-docker
      containers:
      - name: jarvice-api
        image: {{ include "jarvice.registry" . }}/{{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}/jarvice-api:{{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
        imagePullPolicy: Always
{{- else }}
        imagePullPolicy: IfNotPresent
{{- end }}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /jarvice/ready
          initialDelaySeconds: {{ .Values.jarvice_api.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_api.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_api.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_api.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_api.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: http
            path: /jarvice/live
          initialDelaySeconds: {{ .Values.jarvice_api.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jarvice_api.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jarvice_api.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jarvice_api.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jarvice_api.livenessProbe.failureThreshold }}
        env:
          - name: JARVICE_SYSTEM_K8S
{{- if empty .Values.jarvice.JARVICE_SYSTEM_K8S }}
            value: "true"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_SYSTEM_K8S }}"
{{- end }}
          - name: JARVICE_EXPERIMENTAL
{{- if empty .Values.jarvice.JARVICE_EXPERIMENTAL }}
            value: "false"
{{- else }}
            value: "{{ .Values.jarvice.JARVICE_EXPERIMENTAL }}"
{{- end }}
          - name: JARVICE_DAL_URL
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: "http://jarvice-dal.{{ .Release.Namespace }}:8080"
{{- else }}
            value: "http://jarvice-dal.{{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}:8080"
{{- end }}
          - name: JARVICE_API_URL
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: "http://jarvice-api.{{ .Release.Namespace }}:8080"
{{- else }}
            value: "http://jarvice-api.{{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}:8080"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_API_PUBLIC_URL)) }}
          - name: JARVICE_API_PUBLIC_URL
            value: "{{ .Values.jarvice.JARVICE_API_PUBLIC_URL }}"
{{- else if (not (empty .Values.jarvice_api.ingressHost)) }}
          - name: JARVICE_API_PUBLIC_URL
            value: 'https://{{- .Values.jarvice_api.ingressHost -}}{{- .Values.jarvice_api.ingressPath -}}'
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTP_PROXY)) }}
          - name: http_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTP_PROXY }}"
{{- end }}
{{- if (not (empty .Values.jarvice.JARVICE_HTTPS_PROXY)) }}
          - name: https_proxy
            value: "{{ .Values.jarvice.JARVICE_HTTPS_PROXY }}"
{{- end }}
{{- if or .Values.jarvice.JARVICE_HTTPS_PROXY .Values.jarvice.JARVICE_HTTP_PROXY .Values.jarvice.JARVICE_NO_PROXY }}
{{- if (not (empty .Values.jarvice.JARVICE_NO_PROXY)) }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }},{{ .Values.jarvice.JARVICE_NO_PROXY }}'
{{- else }}
          - name: no_proxy
            value: '{{ include "jarvice.no_proxy" . }}'
{{- end }}
{{- end }}
          - name: JARVICE_SCHED_URL
            value: "https://jarvice-scheduler:9443"
          - name: JARVICE_JOBS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
            value: {{ .Release.Namespace }}-jobs
{{- else }}
            value: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
          - name: JARVICE_BUILDS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
            value: {{ .Release.Namespace }}-builds
{{- else }}
            value: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
          - name: JARVICE_PULLS_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
            value: {{ .Release.Namespace }}-pulls
{{- else }}
            value: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_NAMESPACE
{{- if empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
            value: {{ .Release.Namespace }}
{{- else }}
            value: {{ .Values.jarvice.JARVICE_SYSTEM_NAMESPACE }}
{{- end }}
          - name: JARVICE_SYSTEM_REGISTRY
            value: {{ include "jarvice.registry" . }}
          - name: JARVICE_SYSTEM_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_SYSTEM_REPO_BASE }}
          - name: JARVICE_IMAGES_TAG
{{- if .Values.jarvice_api.env }}
{{- if empty .Values.jarvice_api.env.JARVICE_IMAGES_TAG }}
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- else }}
            value: {{ .Values.jarvice_api.env.JARVICE_IMAGES_TAG }}
{{- end }}
{{- else }}
            value: {{ default .Values.jarvice.JARVICE_IMAGES_TAG .Chart.Annotations.tag }}{{- include "jarvice.version" . }}
{{- end }}
          - name: JARVICE_LOCAL_REGISTRY
            value: {{ .Values.jarvice.JARVICE_LOCAL_REGISTRY }}
          - name: JARVICE_LOCAL_REPO_BASE
            value: {{ .Values.jarvice.JARVICE_LOCAL_REPO_BASE }}
{{- if (not (empty .Values.jarvice_dockerbuild.tolerations)) }}
          - name: JARVICE_BUILD_NODE_TOLERATIONS
            value: '{{ .Values.jarvice_dockerbuild.tolerations }}'
{{- else if (not (empty .Values.jarvice.tolerations)) }}
          - name: JARVICE_BUILD_NODE_TOLERATIONS
            value: '{{ .Values.jarvice.tolerations }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.tolerations)) }}
          - name: JARVICE_PULL_NODE_TOLERATIONS
            value: '{{ .Values.jarvice_dockerpull.tolerations }}'
{{- else if (not (empty .Values.jarvice.tolerations)) }}
          - name: JARVICE_PULL_NODE_TOLERATIONS
            value: '{{ .Values.jarvice.tolerations }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerbuild.nodeSelector)) }}
          - name: JARVICE_BUILD_NODE_SELECTOR
            value: '{{ .Values.jarvice_dockerbuild.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_BUILD_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerbuild.nodeAffinity)) }}
          - name: JARVICE_BUILD_NODE_AFFINITY
            value: '{{ .Values.jarvice_dockerbuild.nodeAffinity }}'
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
          - name: JARVICE_BUILD_NODE_AFFINITY
            value: '{{ .Values.jarvice.nodeAffinity }}'
{{- end }}
          - name: JARVICE_BUILD_IMAGE_PULL_POLICY
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
            value: "Always"
{{- else }}
            value: "IfNotPresent"
{{- end }}
          - name: JARVICE_BUILD_RESOURCES_REQUESTS_CPU
            value: "{{ .Values.jarvice_dockerbuild.resources.requests.cpu }}"
          - name: JARVICE_BUILD_RESOURCES_REQUESTS_MEMORY
            value: "{{ .Values.jarvice_dockerbuild.resources.requests.memory }}"
          - name: JARVICE_BUILD_RESOURCES_LIMITS_CPU
            value: "{{ .Values.jarvice_dockerbuild.resources.limits.cpu }}"
          - name: JARVICE_BUILD_RESOURCES_LIMITS_MEMORY
            value: "{{ .Values.jarvice_dockerbuild.resources.limits.memory }}"
{{- if .Values.jarvice_dockerbuild.persistence.enabled }}
          - name: JARVICE_BUILD_PERSISTENCE_ENABLED
            value: "true"
          - name: JARVICE_BUILD_PERSISTENCE_SIZE
            value: "{{ .Values.jarvice_dockerbuild.persistence.size }}"
          - name: JARVICE_BUILD_PERSISTENCE_STORAGECLASS
{{- if (eq "-" .Values.jarvice_dockerbuild.persistence.storageClass) }}
            value: ""
{{- else }}
            value: "{{ .Values.jarvice_dockerbuild.persistence.storageClass }}"
{{- end }}
{{- else }}
          - name: JARVICE_BUILD_PERSISTENCE_ENABLED
            value: "false"
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.nodeSelector)) }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: '{{ .Values.jarvice_dockerpull.nodeSelector }}'
{{- else if (not (empty .Values.jarvice.nodeSelector)) }}
          - name: JARVICE_PULL_NODE_SELECTOR
            value: '{{ .Values.jarvice.nodeSelector }}'
{{- end }}
{{- if (not (empty .Values.jarvice_dockerpull.nodeAffinity)) }}
          - name: JARVICE_PULL_NODE_AFFINITY
            value: '{{ .Values.jarvice_dockerpull.nodeAffinity }}'
{{- else if (not (empty .Values.jarvice.nodeAffinity)) }}
          - name: JARVICE_PULL_NODE_AFFINITY
            value: '{{ .Values.jarvice.nodeAffinity }}'
{{- end }}
          - name: JARVICE_PULL_IMAGE_PULL_POLICY
{{- if and (empty .Values.jarvice.JARVICE_IMAGES_VERSION) (empty .Chart.Annotations.tag) }}
            value: "Always"
{{- else }}
            value: "IfNotPresent"
{{- end }}
{{- $smtpd := printf "jarvice-smtpd.%s:25" .Release.Namespace -}}
{{- if (not (empty .Values.jarvice.JARVICE_SYSTEM_NAMESPACE)) }}
{{- $smtpd = printf "jarvice-smtpd.%s:25" .Values.jarvice.JARVICE_SYSTEM_NAMESPACE -}}
{{- end }}
          - name: JARVICE_MAIL_FROM
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_FROM | indent 12 }}
          - name: JARVICE_MAIL_ADMINS
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_ADMINS | indent 12 }}
          - name: JARVICE_MAIL_SERVER
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_SERVER | replace "jarvice-smtpd:25" $smtpd | indent 12 }}
          - name: JARVICE_MAIL_USERNAME
            value: {{ toYaml .Values.jarvice.JARVICE_MAIL_USERNAME | indent 12 }}
{{- if (not (empty .Values.jarvice.JARVICE_MAIL_PASSWORD)) }}
          - name: JARVICE_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jarvice-mail
                key: JARVICE_MAIL_PASSWORD
{{- end }}
          - name: JARVICE_API_LOGLEVEL
            value: "{{ .Values.jarvice.JARVICE_API_LOGLEVEL }}"
          - name: JARVICE_API_POOL_SIZE
{{- if empty .Values.jarvice_api.env.JARVICE_API_POOL_SIZE }}
            value: "4"
{{- else }}
            value: "{{ .Values.jarvice_api.env.JARVICE_API_POOL_SIZE }}"
{{- end }}
        resources:
{{ toYaml .Values.jarvice_api.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-api
---
{{- if or .Values.jarvice_api.networkPolicy.enabled (and (eq "<nil>" (toString .Values.jarvice_api.networkPolicy.enabled)) .Values.jarvice.networkPolicy.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jarvice-api
spec:
  podSelector:
    matchLabels:
      deployment: jarvice-api
  policyTypes:
  - Ingress
  ingress:
{{- if (empty .Values.jarvice_api.ingressHost) }}
  - {}
{{- else }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
---
{{- end }}
{{- if (empty .Values.jarvice_api.ingressHost) }}
apiVersion: v1
kind: Service
metadata:
  name: jarvice-api-lb
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.jarvice_api.loadBalancerIP }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    deployment: jarvice-api
---
{{- else }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: jarvice-api
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-api
  annotations:
{{- if (not (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion)) }}
{{- if (not (empty .Values.jarvice.ingress.class)) }}
    kubernetes.io/ingress.class: {{ .Values.jarvice.ingress.class }}
{{- end }}
{{- end }}
{{- if and (not (empty .Values.jarvice.ingress.tls.issuer.name)) (and (empty .Values.jarvice.ingress.tls.crt) (empty .Values.jarvice.ingress.tls.key)) }}
    cert-manager.io/issuer: {{ .Values.jarvice.ingress.tls.issuer.name }}
{{- else if and (not (empty .Values.jarvice.ingress.tls.cluster_issuer.name)) (and (empty .Values.jarvice.ingress.tls.crt) (empty .Values.jarvice.ingress.tls.key)) }}
    cert-manager.io/cluster-issuer: {{ .Values.jarvice.ingress.tls.cluster_issuer.name }}
{{- end }}
{{- if .Values.jarvice_api.ingressAnnotations }}
{{- if (kindIs "string" .Values.jarvice_api.ingressAnnotations) }}
{{ toYaml (fromJson .Values.jarvice_api.ingressAnnotations) | indent 4 }}
{{- else }}
{{ toYaml .Values.jarvice_api.ingressAnnotations | indent 4 }}
{{- end }}
{{- end }}
spec:
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if (not (empty .Values.jarvice.ingress.class)) }}
  ingressClassName: {{ .Values.jarvice.ingress.class }}
{{- end }}
{{- end }}
  rules:
  - http:
      paths:
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
{{- if (eq "/api" .Values.jarvice_api.ingressPath) }}
      - backend:
          service:
            name: jarvice-api
            port:
              name: http
        pathType: Prefix
        path: /api
{{- else }}
      - backend:
          service:
            name: jarvice-api
            port:
              name: http
        pathType: Prefix
        path: /
{{- end }}
{{- else }}
{{- if (eq "/api" .Values.jarvice_api.ingressPath) }}
      - backend:
          serviceName: jarvice-api
          servicePort: http
        path: /api
{{- else }}
      - backend:
          serviceName: jarvice-api
          servicePort: http
        path: /
{{- end }}
{{- end }}
{{- if ne "-" .Values.jarvice_api.ingressHost }}
    host: '{{- .Values.jarvice_api.ingressHost -}}'
{{- if or (not (empty .Values.jarvice.ingress.tls.cluster_issuer.name)) (not (empty .Values.jarvice.ingress.tls.issuer.name)) (and (not (empty .Values.jarvice.ingress.tls.crt)) (not (empty .Values.jarvice.ingress.tls.key))) }}
  tls:
  - hosts:
    - '{{- .Values.jarvice_api.ingressHost -}}'
{{- if and (not (empty .Values.jarvice.ingress.tls.crt)) (not (empty .Values.jarvice.ingress.tls.key)) }}
    secretName: 'tls-jarvice'
{{- else }}
    secretName: 'tls-{{- .Values.jarvice_api.ingressHost -}}'
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
