{{- if or .Values.jarvice_scheduler.enabled .Values.jarvice_k8s_scheduler.enabled }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-jobs
{{- if empty .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-jobs
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_JOBS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
spec:
  selector:
    matchLabels:
      jarvice-job: "true"
  maxUnavailable: 0
---
{{- end }}
{{- if (not (eq "downstream" .Values.jarvice.JARVICE_CLUSTER_TYPE)) }}
{{- if .Values.jarvice_api.enabled }}
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-builds
{{- if empty .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-builds
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_BUILDS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
spec:
  selector:
    matchLabels:
      jarvice-build: "true"
  maxUnavailable: 0
---
{{- if (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: jarvice-pulls
{{- if empty .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
  namespace: {{ .Release.Namespace }}-pulls
{{- else }}
  namespace: {{ .Values.jarvice.JARVICE_PULLS_NAMESPACE }}
{{- end }}
  labels:
    {{- include "jarvice.release_labels" . | indent 4 }}
    component: jarvice-system
spec:
  selector:
    matchLabels:
      jarvice-pull: "true"
  maxUnavailable: 0
---
{{- end }}
{{- end }}
