#!/bin/bash

VERSION=v1.2.3
IPALLOC_RANGE=10.32.0.0/12

function usage {
    cat <<EOF
Usage:
    $0 [options]

Options:
    --version <version>     Version to install
                            (Default: $VERSION)

Example:
    $0 --version $VERSION


Notes:
    Be sure that kube-controller-manager is running with --cluster-cidr flag.

Documentation:
    https://github.com/cloudnativelabs/kube-router/blob/master/docs/kubeadm.md
    https://www.kube-router.io/docs/

Example:
    sudo kubeadm init --pod-network-cidr $IPALLOC_RANGE
EOF
}

KUBECTL=$(type -p kubectl)
if [ -z "$KUBECTL" ]; then
    cat <<EOF
Could not find 'kubectl' in PATH.  It may not be installed.
Run 'install-kubectl' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

echo -n "Checking for previously installed pod network addons..."
installed_plugins=$($KUBECTL get --all-namespaces daemonsets -o name | grep -w "^daemonset\..\+/\(weave-net\|kube-flannel\|contiv\|cilium\|calico\)")
if [ -n "$installed_plugins" ]; then
    echo; echo; echo "Only one pod network add-on at a time can be used."
    echo "We found that the following has already been deployed:"
    echo "$installed_plugins"
    echo; echo "Cannot continue.  Exiting..."
    exit 1
fi
echo "OK"

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        --version)
            VERSION=$2
            shift; shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

set -e

echo; echo "* Deploying version: $VERSION"

# See this link for more information on Kube-router configuration options:
# https://www.kube-router.io/docs/
$KUBECTL apply -f "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml"
image=docker.io/cloudnativelabs/kube-router:$VERSION
$KUBECTL --namespace kube-system patch daemonset kube-router \
    --patch "{\"spec\": {\"template\": {\"spec\": {\"containers\": [{\"name\": \"kube-router\", \"image\": \"$image\"}], \"tolerations\": [{\"effect\": \"NoSchedule\", \"operator\": \"Exists\"}]}}}}"

echo
echo "* Deployment successful..."

# The following should already be set on all worker nodes:
# $ sysctl net.bridge.bridge-nf-call-iptables=1

echo
echo "For advanced configuration and troubleshooting, please see the official Kube-router documentation:"
echo "https://www.kube-router.io/docs/"

