#!/bin/bash

IPALLOC_RANGE=10.32.0.0/12

function usage {
    cat <<EOF
Usage:
    $0

Notes:
    Be sure that kube-controller-manager is running with --cluster-cidr flag.

Documentation:
    https://github.com/cloudnativelabs/kube-router/blob/master/docs/kubeadm.md
    https://www.kube-router.io/docs/

Example:
    sudo kubeadm init --pod-network-cidr $IPALLOC_RANGE
EOF
}

KUBECTL=$(type -p kubectl)
if [ -z "$KUBECTL" ]; then
    cat <<EOF
Could not find 'kubectl' in PATH.  It may not be installed.
Run 'install-kubectl' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

set -e

echo "* Deploying..."

# See this link for more information on Kube-router configuration options:
# https://www.kube-router.io/docs/
$KUBECTL apply -f "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml"
$KUBECTL --namespace kube-system patch daemonset kube-router --patch '{"spec": {"template": {"spec": {"tolerations": [{"effect": "NoSchedule", "operator": "Exists"}]}}}}'

echo
echo "* Deployment successful..."

# The following should already be set on all worker nodes:
# $ sysctl net.bridge.bridge-nf-call-iptables=1

echo
echo "For advanced configuration and troubleshooting, please see the official Kube-router documentation:"
echo "https://www.kube-router.io/docs/"

