#!/bin/bash

IPALLOC_RANGE=10.32.0.0/12  # <-- weave-net default

function usage {
    cat <<EOF
Usage:
    $0 [options]

Options:
    --ipalloc-range <ip_range>  IP address range used by Weave Net
                                (Default: $IPALLOC_RANGE)

Example:
    $0 --ipalloc-range 10.32.0.0/12
EOF
}

KUBECTL=$(type -p kubectl)
if [ -z "$KUBECTL" ]; then
    cat <<EOF
Could not find 'kubectl' in PATH.  It may not be installed.
Run 'install-kubectl' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

echo -n "Checking for previously installed pod network addons..."
installed_plugins=$($KUBECTL get --all-namespaces daemonsets -o name | grep -w "^daemonset.extensions/\(kube-router\|kube-flannel\|contiv\|cilium\|calico-node\)")
if [ -n "$installed_plugins" ]; then
    echo; echo "Only one pod network add-on at a time can be used."
    echo "We found that the following has already been deployed:"
    echo "$installed_plugins"
    echo; echo "Cannot continue.  Exiting..."
    exit 1
fi
echo "OK"

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        --ipalloc-range)
            IPALLOC_RANGE=$2
            shift; shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

set -e

echo; echo "* Deploying...  IPALLOC_RANGE=$IPALLOC_RANGE"

# See this link for more information on Weave Net configuration options:
# https://github.com/weaveworks/weave/blob/master/site/kubernetes/kube-addon.md#-changing-configuration-options
$KUBECTL apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE=$IPALLOC_RANGE"

echo
echo "* Deployment successful...  IPALLOC_RANGE=$IPALLOC_RANGE"

# The following should already be set on all worker nodes:
# $ sysctl net.bridge.bridge-nf-call-iptables=1

echo
echo "For advanced configuration and troubleshooting, please see the official Weave Net setup guide:"
echo "https://www.weave.works/docs/net/latest/kubernetes/kube-addon/"

