#!/bin/bash

default_cert_file=cert.pem
default_key_file=cert.key
load_balancer_ip=10.10.10.10

dashboard_enabled=false
dashboard_domain=traefik-dashboard.mydomain.com

helm upgrade traefik stable/traefik --namespace kube-system \
    --install --reset-values \
    \
    --set rbac.enabled=true \
    \
    --set nodeSelector."kubernetes\.io/arch"=amd64 \
    --set nodeSelector."node-role\.kubernetes\.io/jarvice-system"="" \
    \
    --set tolerations[0]."key"="node-role\.kubernetes\.io/jarvice-system" \
    --set tolerations[0]."effect"="NoSchedule" \
    --set tolerations[0]."operator"="Exists" \
    \
    --set loadBalancerIP=$load_balancer_ip \
    --set dashboard.enabled=$dashboard_enabled \
    --set dashboard.domain=$dashboard_domain \
    \
    --set ssl.enabled=true \
    --set ssl.enforced=true \
    --set ssl.permanentRedirect=true \
    --set ssl.insecureSkipVerify=true \
    --set ssl.generateTLS=false \
    --set ssl.defaultCert="$(cat $default_cert_file | base64 -w 0)" \
    --set ssl.defaultKey="$(cat $default_key_file | base64 -w 0)" \
    \
    --set replicas=3 \
    --set memoryRequest=1Gi --set memoryLimit=1Gi \
    --set cpuRequest=1 --set cpuLimit=1 

