#!/bin/bash

kubectl proxy &> /dev/null &
proxy_pid="$!"
curl -sSL "localhost:8001/api/v1/nodes/$(kubectl get no | awk 'FNR==2{ print $1 }')/proxy/configz" | jq -r .kubeletconfig.clusterDomain
kill -9 "$proxy_pid"
