#!/bin/bash

jarvice_chart_dir=$(realpath --relative-to=$(pwd) $(dirname $0)/..)
values_yaml=$jarvice_chart_dir/values.yaml

JARVICE_REGISTRY=us-docker.pkg.dev
JARVICE_REPOSITORY=jarvice-system/images
JARVICE_PUBLIC_REPOSITORY=jarvice/images
JARVICE_VERSION=

SAVE_DIR=
PUSH_REGISTRY=
PUSH_REPOSITORY=$JARVICE_REPOSITORY

DOCKER=docker

JARVICE_IMAGES="jarvice-slurm-scheduler jarvice-dal jarvice-scheduler jarvice-sched-pass jarvice-k8s-scheduler jarvice-pod-scheduler jarvice-api jarvice-mc-portal init initv2 jarvice-appsync jarvice-dockerbuild jarvice-dockerpull jarvice-keycloak jarvice-bird jarvice-bird-portal jarvice-bird-server jarvice-api-v1"
JARVICE_PUBLIC_IMAGES="init-kns"
EXTRA_IMAGES=$(grep -iw image: $values_yaml 2>/dev/null | sed 's/#.*//' | awk '{print $2}' | sort | uniq)
EXTRA_IMAGES+=$(grep -iw JARVICE_.*_IMAGE: $values_yaml | sed 's/#.*//' | awk '{print $2}' | sed 's/\"//g' | sort | uniq)
EXTRA_IMAGES+=" quay.io/jetstack/trust-manager:v0.9.2 quay.io/jetstack/cert-manager-package-debian:20210119.0"

function usage {
    cat <<EOF
Usage:
    $0 [options]

Options:
    --jarvice-version <version>     JARVICE version to pull (required)
    --save <directory>              $DOCKER save images to dir after pull
    --push-registry <registry>      Registry to push images to
    --push-repository <repository>  Repository/namespace to push JARVICE system
                                    images to (Default: $PUSH_REPOSITORY)
    --remove                        Remove local images after successful push
    --docker <executable>           Docker executable (Default: $DOCKER)

Example:
$0 \\
    --jarvice-version jarvice-master-3.0.0-1.202005151836 \\
    --push-registry localhost:5000 \\
    --push-repository $PUSH_REPOSITORY
EOF
}

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        --jarvice-version)
            JARVICE_VERSION=$2
            shift; shift
            ;;
        --save)
            SAVE_DIR=$2
            shift; shift
            ;;
        --push-registry)
            PUSH_REGISTRY=$2
            shift; shift
            ;;
        --push-repository)
            PUSH_REPOSITORY=$2
            shift; shift
            ;;
        --remove)
            REMOVE=1
            shift;
            ;;
        --docker)
            DOCKER=$2
            shift; shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

DOCKER=$(type -p $DOCKER)
if [ -z "$DOCKER" ]; then
    cat <<EOF
Could not find 'docker' in PATH.  It may not be installed.
Run 'install-docker' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

$DOCKER info >/dev/null 2>&1
[ "$?" != "0" ] && echo "User '$USER' is not able to communicate with the docker daemon" && exit 1

[ -z "$JARVICE_VERSION" ] && usage && exit 1

set -e

JARVICE_REG_REPO=$JARVICE_REGISTRY/$JARVICE_REPOSITORY
PUSH_REG_REPO=
[ -n "$PUSH_REGISTRY" ] && PUSH_REG_REPO=$PUSH_REGISTRY/$PUSH_REPOSITORY
for i in $JARVICE_IMAGES; do
    $DOCKER pull $JARVICE_REG_REPO/$i:$JARVICE_VERSION
    [ -n "$SAVE_DIR" ] && $DOCKER save $JARVICE_REG_REPO/$i:$JARVICE_VERSION | gzip >$SAVE_DIR/$(echo $JARVICE_REG_REPO/$i:$JARVICE_VERSION | sed -e 's|/|~|g').tar.gz
    if [ -n "$PUSH_REG_REPO" ]; then
        $DOCKER tag $JARVICE_REG_REPO/$i:$JARVICE_VERSION $PUSH_REG_REPO/$i:$JARVICE_VERSION
        $DOCKER push $PUSH_REG_REPO/$i:$JARVICE_VERSION
        [ -n "$REMOVE" ] && $DOCKER rmi $PUSH_REG_REPO/$i:$JARVICE_VERSION $JARVICE_REG_REPO/$i:$JARVICE_VERSION
    fi
done

JARVICE_REG_REPO=$JARVICE_REGISTRY/$JARVICE_PUBLIC_REPOSITORY
PUSH_REG_REPO=
[ -n "$PUSH_REGISTRY" ] && PUSH_REG_REPO=$PUSH_REGISTRY/$PUSH_REPOSITORY
for i in $JARVICE_PUBLIC_IMAGES; do
    $DOCKER pull $JARVICE_REG_REPO/$i:$JARVICE_VERSION
    [ -n "$SAVE_DIR" ] && $DOCKER save $JARVICE_REG_REPO/$i:$JARVICE_VERSION | gzip >$SAVE_DIR/$(echo $JARVICE_REG_REPO/$i:$JARVICE_VERSION | sed -e 's|/|~|g').tar.gz
    if [ -n "$PUSH_REG_REPO" ]; then
        $DOCKER tag $JARVICE_REG_REPO/$i:$JARVICE_VERSION $PUSH_REG_REPO/$i:$JARVICE_VERSION
        $DOCKER push $PUSH_REG_REPO/$i:$JARVICE_VERSION
        [ -n "$REMOVE" ] && $DOCKER rmi $PUSH_REG_REPO/$i:$JARVICE_VERSION $JARVICE_REG_REPO/$i:$JARVICE_VERSION
    fi
done

for i in $EXTRA_IMAGES; do
    $DOCKER pull $i
    [ -n "$SAVE_DIR" ] && $DOCKER save $i | gzip >$SAVE_DIR/$(echo $i | sed -e 's|/|~|g').tar.gz
    if [ -n "$PUSH_REGISTRY" ]; then
        push_image=$PUSH_REGISTRY/$(echo ${i#*/})
        $DOCKER tag $i $push_image
        $DOCKER push $push_image
        [ -n "$REMOVE" ] && $DOCKER rmi $push_image $i
    fi
done

