#!/bin/bash

namespace=jarvice-system
file=$namespace.sql.gz

function usage {
    cat <<EOF
Usage:
    $0 [options]

Options:
    --namespace <kube_namespace>    Kubernetes namespace of JARVICE deployment
                                    (Default: $namespace)
    --file <sql_backup_file>        File backup to create (gzipped)
                                    (Default: $file)

Example:
    $0 --namespace jarvice-system --file $namespace.sql.gz
EOF
}

KUBECTL=$(type -p kubectl)
if [ -z "$KUBECTL" ]; then
    cat <<EOF
Could not find 'kubectl' in PATH.  It may not be installed.
Run 'install-kubectl' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        --namespace)
            namespace=$2
            shift; shift
            ;;
        --file)
            file=$2
            shift; shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

pod=$("$KUBECTL" -n $namespace get pods \
        -l component=jarvice-dal \
        --field-selector=status.phase=Running \
        -o jsonpath={.items[0].metadata.name})
[ -z "$pod" ] && echo "* Could not find jarvice-dal pod in $namespace namespace...Exiting..." && exit 1
cmd='mysqldump '
cmd+=' --user="$JARVICE_SITE_DBUSER" --password="$JARVICE_SITE_DBPASSWD"'
cmd+=' --host="$JARVICE_SITE_DBHOST" nimbix'
echo "* Dumping JARVICE database from $namespace namespace to $file..."
"$KUBECTL" -n $namespace exec $pod -- bash -c "$cmd" | gzip >$file
echo; echo "* Successfully dumped JARVICE database from $namespace namespace to $file..."

