#!/bin/bash

namespace=jarvice-system

function usage {
    cat <<EOF
Usage:
    $0 [options]

Options:
    --namespace <kube_namespace>    Kubernetes namespace of JARVICE deployment
                                    (Default: $namespace)

Example:
    $0 --namespace jarvice-system
EOF
}

KUBECTL=$(type -p kubectl)
if [ -z "$KUBECTL" ]; then
    cat <<EOF
Could not find 'kubectl' in PATH.  It may not be installed.
Run 'install-kubectl' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        --namespace)
            namespace=$2
            shift; shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

pod=$("$KUBECTL" -n $namespace get pods \
        -l component=jarvice-db \
        --field-selector=status.phase=Running \
        -o jsonpath={.items[0].metadata.name})
[ -z "$pod" ] && echo "* Could not find jarvice-db pod in $namespace namespace...Exiting..." && exit 1
cmd='mariadb-upgrade '
cmd+=' --user="root" --password="$MYSQL_ROOT_PASSWORD"'
echo "* Upgrading JARVICE database in $namespace namespace..."
"$KUBECTL" -n $namespace exec $pod -- bash -c "$cmd"
echo; echo "* Successfully upgraded JARVICE database in $namespace namespace..."
sleep 1

echo; echo "* Restarting JARVICE database in $namespace namespace..."
"$KUBECTL" -n $namespace rollout restart deployment/jarvice-db
"$KUBECTL" -n $namespace rollout status deployment/jarvice-db --watch=true

echo; echo "* Restarting JARVICE DAL in $namespace namespace..."
"$KUBECTL" -n $namespace rollout restart deployment/jarvice-dal
"$KUBECTL" -n $namespace rollout status deployment/jarvice-dal --watch=true

