#!/bin/bash

namespace=jarvice-system

function usage {
    cat <<EOF
Usage:
    $0 [options]

Options:
    --namespace <kube_namespace>    Kubernetes namespace of JARVICE deployment
                                    (Default: $namespace)
    --query <sql_query>             SQL query to execute (required)

Examples:
    $0 --namespace jarvice-system --query "SELECT job_submit_time, job_start_time FROM jobs;"

    $0 --query "SELECT job_start_time-job_submit_time FROM jobs WHERE job_start_time!=0;"

    $0 --query "SELECT AVG(job_start_time-job_submit_time) FROM jobs WHERE job_start_time!=0;"

EOF
}

KUBECTL=$(type -p kubectl)
if [ -z "$KUBECTL" ]; then
    cat <<EOF
Could not find 'kubectl' in PATH.  It may not be installed.
Run 'install-kubectl' from the 'jarvice-helm/scripts' directory to install it.
EOF
    exit 1
fi

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        --namespace)
            namespace=$2
            shift; shift
            ;;
        --query)
            query=$2
            shift; shift
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

[ -z "$query" ] && usage && exit 1

pod=$($KUBECTL -n $namespace get pods \
        -l component=jarvice-dal \
        --field-selector=status.phase=Running \
        -o jsonpath={.items[0].metadata.name})
[ -z "$pod" ] && echo "* Could not find jarvice-db pod in $namespace namespace...Exiting..." && exit 1
cmd='mariadb '
cmd+=' --user="$JARVICE_SITE_DBUSER" --password="$JARVICE_SITE_DBPASSWD"'
cmd+=' --host="$JARVICE_SITE_DBHOST" nimbix'
echo "* Running query on JARVICE database in $namespace namespace..."; echo
$KUBECTL -n $namespace exec $pod -- bash -c "echo '$query' | $cmd"

